---
title: The evolution of environmental issues in Chilean foreign policy discourse.
  Applying Structural Topic Modelling to the UN General Debate interventions by Chilean
  officials from 1971 to 2022
author: "Vicente Opazo Cortés"
date: "2022-10-17"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library_packages, warning=FALSE, include=FALSE}
library(pacman)
pacman::p_load(readr, 
               stm, 
               dplyr, 
               openxlsx, 
               readtext, 
               quanteda, 
               igraph)

```

```{r download_data, eval=FALSE, warning=FALSE, include=FALSE}
url <- "https://www.researchgate.net/profile/Vicente_Opazo/publication/363844089_UN_General_Debate_Corpus_Chile_1971-2022/data/634ca5809cb4fe44f32f306d/UNGDC-Chile-1971-2022.zip" 
download.file(url, "UNGC_Chile.zip")
unzip("UNGC_Chile.zip")
```

```{r download_metadata, eval=FALSE, warning=FALSE, include=FALSE}
url2 <- "https://www.researchgate.net/profile/Vicente_Opazo/publication/363844089_UN_General_Debate_Corpus_Chile_1971-2022/data/63687a2237878b3e878a348f/metadata-UNGDC-Chile-1971-2022.xlsx" 
download.file(url2, "metadata_UNGDC_Chile_1971_2022.xlsx", quiet = TRUE, mode = "wb")
```

```{r creating_dataset_from_data, warning=FALSE, include=FALSE}
documents <- readtext("UNGDC_Chile_1971_2022", 
                     ignore_missing_files = FALSE, 
                     text_field = NULL,
                     docid_field = NULL)
```

```{r creating_dataset_from_metadata, warning=FALSE, include=FALSE}
meta_ungdc_chile <- read.xlsx("metadata_UNGDC_Chile_1971_2022.xlsx", sheet = 1)
meta_ungdc_chile$Gov.Rating <- as.factor(meta_ungdc_chile$Gov.Rating)
meta_ungdc_chile$Year <- as.integer(meta_ungdc_chile$Year)
```

```{r data_pre-processing, warning=FALSE, include=FALSE}
data_proc <- textProcessor(documents$text, metadata = meta_ungdc_chile)
output <- prepDocuments(data_proc$documents, data_proc$vocab, data_proc$meta, lower.thresh = 1, upper.thresh = 52)  
docs <- output$documents
vocab <- output$vocab
meta <-output$meta
```

```{r exploring_optimal_K, echo=FALSE, warning=FALSE}
findingk <- searchK(output$documents, output$vocab, K = c(3:20), prevalence =~ Gov.Rating + Year, data = meta, verbose=FALSE)
 plot(findingk) #optimal K=5:10
```

```{r running_STM_plus_visualizing_results, echo=FALSE, warning=FALSE}
STM <- stm(documents = output$documents, vocab = output$vocab,
                  K = 5, prevalence =~ Gov.Rating + Year,
                  max.em.its = 75, data = output$meta, 
               init.type = "Spectral", verbose = FALSE) 
plot(STM)
```

```{r exploring_STM, eval=FALSE, warning=FALSE, include=FALSE}
labelTopics(STM) #check probability (prob) + frequency & exclusivity (frex) 
findThoughts(STM, texts = documents$text,
     n = 1, topics = 3)
findThoughts(STM, texts = documents$text,
     n = 1, topics = 4)
findThoughts(STM, texts = documents$text,
     n = 1, topics = 5)
set.seed(930)
cloud(STM, topic=1, max.words = 30)
cloud(STM, topic=2, max.words = 30)
cloud(STM, topic=3, max.words = 30)
cloud(STM, topic=4, max.words = 30)
cloud(STM, topic=5, max.words = 30)
```

```{r label_topics_STM, echo=FALSE, warning=FALSE}
plot(STM, type = "labels", n = 7, labeltype = "prob", topic.names = c("1. Human rights, democracy and economic devel.", "2. Chilean internal politics", "3. UN relevant bodies' role on Latin American issues", "4. Co-operation in line with non-intervention principle", "5. Environmental issues"), width = 80)
set.seed(87)
cloud(STM, topic=3, max.words = 20)
set.seed(89)
cloud(STM, topic=5, max.words = 20)
```

```{r covs_effect_prediction_models, echo=FALSE, warning=FALSE}
predict_topics <- estimateEffect(formula =~ Gov.Rating + Year, stmobj = STM, metadata = output$meta, uncertainty = "Global")
plot(predict_topics, covariate = "Gov.Rating", topics = 3,
 model = STM, method = "pointestimate",
 xlab = "Mean topic proportion: UN relevant bodies' role on Latin American issues", 
 main = "Effect of Political Position (Left-Right Axis)", 
 labeltype = "custom", 
 custom.labels = c("Left-wing", "Centre-right", "Centre-left", "Centre", "Right-wing"))

plot(predict_topics, covariate = "Gov.Rating", topics = 4,
 model = STM, method = "pointestimate", 
 xlab = "Mean topic proportion: Co-operation in line with non-intervention principle",
 main = "Effect of Political Position (Left-Right Axis)", 
 labeltype = "custom", 
 custom.labels = c("Left-wing", "Centre-right", "Centre-left", "Centre", "Right-wing"))

plot(predict_topics, covariate = "Gov.Rating", topics = 5,
 model = STM, method = "pointestimate",
 xlab = "Mean topic proportion: Environmental issues",
 main = "Effect of Political Position (Left-Right Axis)", 
 labeltype = "custom", 
 custom.labels = c("Left-wing", "Centre-right", "Centre-left", "Centre", "Right-wing"))
```

```{r covs_effect_prediction_models_reference_model_1, warning=FALSE, include=FALSE}
plot(predict_topics, covariate = "Gov.Rating", topics = 1, #experiment
 model = STM, method = "pointestimate",
 main = "Effect of Political Position (Left-Right Axis)")
```


```{r covs_effect_prediction_models_reference_model_2, echo=FALSE, warning=FALSE}
plot(predict_topics, covariate = "Year", method = "continuous", topics = c(5),
model = STM, xlab = "Time in years (1971-2022)")
```
```{r covs_effect_prediction_models_reference_model_3, echo=FALSE, warning=FALSE}
plot(predict_topics, covariate = "Year", method = "continuous", topics = c(5, 3, 4),
model = STM, xlab = "Time in years (1971-2022)")
```